---
- name: "Kubernetes Apps | Lay Down MetalLB"
  become: true
  template: { src: "{{ item }}.j2", dest: "{{ kube_config_dir }}/{{ item }}" }
  with_items: ["metallb.yml", "metallb-config.yml"]
  register: "rendering"
  when:
    - "inventory_hostname == groups['kube-master'][0]"

- name: metallb-all
  blockinfile:
    path: /tmp/metallb-all.yml
    block: "{{ lookup('file', kube_config_dir + '/' + item.item.file) }}"
    create: true
    marker: "# {mark} {{ item.item.file }}"
  with_items:
    - "{{ rendering.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: "Kubernetes Apps | Install and configure MetalLB"
  kube:
    kubectl: "{{bin_dir}}/kubectl"
    filename: "/tmp/metallb-all.yml"
    state: "{{ item.changed | ternary('latest','present') }}"
  become: true
  when:
    - "inventory_hostname == groups['kube-master'][0]"
