---
- name: Set cert dir
  set_fact:
    calico_cert_dir: "{{ canal_cert_dir }}"
  when:
    - kube_network_plugin == 'canal'
  tags:
    - facts
    - canal

- name: Create calico-kube-controllers manifests
  template:
    src: "{{item.file}}.j2"
    dest: "{{kube_config_dir}}/{{item.file}}"
  with_items:
    - {name: calico-kube-controllers, file: calico-kube-controllers.yml, type: deployment}
    - {name: calico-kube-controllers, file: calico-kube-sa.yml, type: sa}
    - {name: calico-kube-controllers, file: calico-kube-cr.yml, type: clusterrole}
    - {name: calico-kube-controllers, file: calico-kube-crb.yml, type: clusterrolebinding}
  register: calico_kube_manifests
  when:
    - inventory_hostname == groups['kube-master'][0]
    - rbac_enabled or item.type not in rbac_resources

- name: calico-kube-controllers-all
  blockinfile:
    path: /tmp/calico-kube-controllers-all.yml
    block: "{{ lookup('file', kube_config_dir + '/' + item.item.file) }}"
    create: true
    marker: "# {mark} {{ item.item.file }}"
  with_items:
    - "{{ calico_kube_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0] and not item is skipped

- name: Start of Calico kube controllers
  kube:
    namespace: "kube-system"
    kubectl: "{{bin_dir}}/kubectl"
    filename: "/tmp/calico-kube-controllers-all.yml"
    state: "latest"
  when:
    - inventory_hostname == groups['kube-master'][0]
